# Generated by Django 5.0.6 on 2024-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C')])),
                ('season', models.CharField(blank=True, choices=[('AD', 'Advent'), ('CH', 'Christmas'), ('EP', 'Epiphany'), ('LE', 'Lent'), ('EA', 'Easter'), ('PE', 'Pentecost')], max_length=2, null=True)),
                ('color', models.CharField(choices=[('WH', 'White'), ('RD', 'Red'), ('GR', 'Green'), ('VI', 'Violet')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture', models.CharField(max_length=300)),
                ('days', models.ManyToManyField(to='lectionary.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='lessons',
            field=models.ManyToManyField(to='lectionary.lesson'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['name'], name='lectionary__name_3faa50_idx'),
        ),
    ]
