# Generated by Django 5.0.6 on 2024-06-29 16:52

import json
from django.db import migrations


def seed_day_data(apps):
    Day = apps.get_model("lectionary", "Day")
    Year = apps.get_model("lectionary", "Year")
    with open("../lectionary.json") as f:
        data = json.load(f)

    for day_name, v in data.items():
        if day_name == "Christmas Day" or day_name == "Easter Day":
            for service_name, years in v.items():
                for year_name in years:
                    if year_name == "Year A":
                        day = Day(name=f"{day_name}: {service_name}", year=Year.A)
                    elif year_name == "Year B":
                        day = Day(name=f"{day_name}: {service_name}", year=Year.B)
                    else:
                        day = Day(name=f"{day_name}: {service_name}", year=Year.C)
                    day.save()
        else:
            for year_name in v:
                if year_name == "Year A":
                    day = Day(name=day_name, year=Year.A)
                elif year_name == "Year B":
                    day = Day(name=day_name, year=Year.B)
                else:
                    day = Day(name=day_name, year=Year.C)
                day.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0001_initial"),
    ]

    operations = []
